name: CI docker

on:
  push:
    branches:
      - develop
      - master
      - GPL-769-cherrypicked-samples-view-revisited
    paths-ignore:
      - "README.md"
    tags:
      - uat-*
      - release-*
      - v*
env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}
  EVENT_WAREHOUSE_IMAGE: docker.pkg.github.com/sanger/event_warehouse/event_warehouse:gpl769_test_cp_view

jobs:
  build_and_test_job:
    runs-on: ubuntu-18.04
    env:
      DBHOST: 127.0.0.1 # If we use localhost, rails tries to use a socket
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: null
          MYSQL_DATABASE: unified_warehouse_test
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: >-
          docker build .
          --file Dockerfile
          --tag docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
      - name: Run Rubocop against the image
        run: >-
          docker run --network host --env DBHOST=127.0.0.1
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} 
          bundle exec rubocop
      - name: Initialize Unified warehouse testing database
        run: >-
          docker run --network host --env DBHOST=127.0.0.1 --env RAILS_ENV=test
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} 
          bundle exec rake db:setup
      - name: Run tests against the image
        run: >-
          docker run --network host --env DBHOST=127.0.0.1
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} 
          bundle exec rspec
      - name: Login to registry
        run: >-
          docker login
          -u ${{ github.actor }}
          -p ${{ secrets.GITHUB_TOKEN }}
          docker.pkg.github.com
      - name: Pull Event warehouse image
        run: >- 
          docker pull ${EVENT_WAREHOUSE_IMAGE}
      - name: Initialize Event warehouse testing database
        run: >-
          docker run --network host --env DBHOST=127.0.0.1 --env RAILS_ENV=test
          -v ${GITHUB_WORKSPACE}/spec/data/test_event_wh_seed.rb:/code/db/seed.rb
          ${EVENT_WAREHOUSE_IMAGE}
          bundle exec rake db:setup db:seed
      - name: Seed Event warehouse testing database
        run: >-
          docker run --network host --env DBHOST=127.0.0.1 --env RAILS_ENV=test
          ${EVENT_WAREHOUSE_IMAGE}
          bundle exec rails runner /code/spec/data/integration/seed_for_unified_wh.rb
      - name: Create the views
        run: >-
          docker run --network host --env DBHOST=127.0.0.1
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} 
          bundle exec rake db:views:schema:load
      - name: Run integration tests
        run: >-
          docker run --network host --env DBHOST=127.0.0.1
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} 
          bundle exec rspec --tag integration
      - name: Publish image with image tag being either develop/master/<tag_name>
        run: >-
          docker push
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
